import java.awt.*;
import java.net.*;
import javax.swing.*;
import java.io.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author M_M NYEMBO'S
 */
public class Search extends javax.swing.JFrame {
    static BufferedReader br = null;
    static Socket soc = null;
    static PrintWriter pw = null;
    Connect conn = new Connect();
    Help he = new Help();
    Functionality fu = new Functionality();
    About ab = new About();
    Insert in = new Insert();
    Delete del = new Delete();
    Admin adm = new Admin();
    MiniExiCanc clos = new MiniExiCanc();
    
    
    public Search() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        LogomovieMaxx = new javax.swing.JLabel();
        jTsearch = new javax.swing.JTextField();
        jBsearch = new javax.swing.JButton();
        jBclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAdesc = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMadm = new javax.swing.JMenu();
        jMenuIinsert = new javax.swing.JMenuItem();
        jMenuItedelete = new javax.swing.JMenuItem();
        jMenuItadm = new javax.swing.JMenuItem();
        jMfunc = new javax.swing.JMenu();
        jMenuItfun = new javax.swing.JMenuItem();
        jMhelp = new javax.swing.JMenu();
        jMenuIthelp = new javax.swing.JMenuItem();
        jMenuItabout = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 29, 55));

        LogomovieMaxx.setIcon(new javax.swing.ImageIcon("C:\\Users\\M_M NYEMBO'S\\OneDrive\\Desktop\\free-vector-movie-max_066186_movie-max.png")); // NOI18N
        LogomovieMaxx.setToolTipText("Welcome, Please login and Enjoy !");

        jTsearch.setBackground(new java.awt.Color(255, 255, 255));
        jTsearch.setFont(new java.awt.Font("Lucida Sans", 1, 17)); // NOI18N
        jTsearch.setForeground(new java.awt.Color(2, 16, 46));
        jTsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsearchActionPerformed(evt);
            }
        });

        jBsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\M_M NYEMBO'S\\OneDrive\\Desktop\\Search.png")); // NOI18N
        jBsearch.setToolTipText("Search!");
        jBsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchActionPerformed(evt);
            }
        });

        jBclose.setIcon(new javax.swing.ImageIcon("C:\\Users\\M_M NYEMBO'S\\OneDrive\\Desktop\\Close.png")); // NOI18N
        jBclose.setToolTipText("Close!");
        jBclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Close button");

        jTextAdesc.setEditable(false);
        jTextAdesc.setBackground(new java.awt.Color(23, 62, 99));
        jTextAdesc.setColumns(20);
        jTextAdesc.setRows(5);
        jScrollPane1.setViewportView(jTextAdesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(LogomovieMaxx, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBclose, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBclose, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LogomovieMaxx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar2.setBackground(new java.awt.Color(224, 120, 64));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jMadm.setBackground(new java.awt.Color(224, 120, 64));
        jMadm.setForeground(new java.awt.Color(255, 255, 255));
        jMadm.setText("Administrator");

        jMenuIinsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuIinsert.setBackground(new java.awt.Color(224, 120, 64));
        jMenuIinsert.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuIinsert.setForeground(new java.awt.Color(255, 255, 255));
        jMenuIinsert.setText("Insert movie");
        jMenuIinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIinsertActionPerformed(evt);
            }
        });
        jMadm.add(jMenuIinsert);

        jMenuItedelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItedelete.setBackground(new java.awt.Color(224, 120, 64));
        jMenuItedelete.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItedelete.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItedelete.setText("Delete movie");
        jMenuItedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItedeleteActionPerformed(evt);
            }
        });
        jMadm.add(jMenuItedelete);

        jMenuItadm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItadm.setBackground(new java.awt.Color(224, 120, 64));
        jMenuItadm.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItadm.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItadm.setText("Administrator");
        jMenuItadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItadmActionPerformed(evt);
            }
        });
        jMadm.add(jMenuItadm);

        jMenuBar2.add(jMadm);

        jMfunc.setBackground(new java.awt.Color(224, 120, 64));
        jMfunc.setForeground(new java.awt.Color(255, 255, 255));
        jMfunc.setText("Functionality");

        jMenuItfun.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItfun.setBackground(new java.awt.Color(224, 120, 64));
        jMenuItfun.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItfun.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItfun.setText("Functionality");
        jMenuItfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItfunActionPerformed(evt);
            }
        });
        jMfunc.add(jMenuItfun);

        jMenuBar2.add(jMfunc);

        jMhelp.setBackground(new java.awt.Color(224, 120, 64));
        jMhelp.setForeground(new java.awt.Color(255, 255, 255));
        jMhelp.setText("Help");

        jMenuIthelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuIthelp.setBackground(new java.awt.Color(224, 120, 64));
        jMenuIthelp.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuIthelp.setForeground(new java.awt.Color(255, 255, 255));
        jMenuIthelp.setText("Help");
        jMenuIthelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIthelpActionPerformed(evt);
            }
        });
        jMhelp.add(jMenuIthelp);

        jMenuItabout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItabout.setBackground(new java.awt.Color(224, 120, 64));
        jMenuItabout.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jMenuItabout.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItabout.setText("About");
        jMenuItabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItaboutActionPerformed(evt);
            }
        });
        jMhelp.add(jMenuItabout);

        jMenuBar2.add(jMhelp);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIinsertActionPerformed
       in.show();
    }//GEN-LAST:event_jMenuIinsertActionPerformed

    private void jBcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcloseActionPerformed
        clos.show();
        
    }//GEN-LAST:event_jBcloseActionPerformed

    private void jBsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchActionPerformed
          Send(jBsearch.getText());
           
    }//GEN-LAST:event_jBsearchActionPerformed

    private void jTsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsearchActionPerformed

    }//GEN-LAST:event_jTsearchActionPerformed

    private void jMenuItaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItaboutActionPerformed
        ab.show();
    }//GEN-LAST:event_jMenuItaboutActionPerformed

    private void jMenuIthelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIthelpActionPerformed
        he.show();
    }//GEN-LAST:event_jMenuIthelpActionPerformed

    private void jMenuItfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItfunActionPerformed
        fu.show();
    }//GEN-LAST:event_jMenuItfunActionPerformed

    private void jMenuItedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItedeleteActionPerformed
      del.show();
    }//GEN-LAST:event_jMenuItedeleteActionPerformed

    private void jMenuItadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItadmActionPerformed
      adm.show();
      Search sea = new Search();
            
    }//GEN-LAST:event_jMenuItadmActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Send(String mg){
        try{
            pw = new PrintWriter(soc.getOutputStream(), true);
            String server;
            if(mg != null){
                jTextAdesc.append("Client" + mg);
                jTextAdesc.append("\n");
                pw.println("Search " + mg);
            }
        }catch(IOException e){
            System.out.println(e.toString());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
        try{
            soc = new Socket("127.0.0.1", 19000);
            br = new BufferedReader(new InputStreamReader(soc.getInputStream()));
            String mg = "";
            String server;
            while ((server = br.readLine()) != null){
            mg = server.toString();
            }
                try{
                jTextAdesc.append("From server: " + mg);
                jTextAdesc.setWrapStyleWord(true);
                jTextAdesc.setLineWrap(true);
                jTextAdesc.append("\n");
            }catch(NullPointerException e){
                    System.out.println(e.toString());
            }if(server.equals("exit")){
                System.exit(0);
            }
            
            
        }catch(UnknownHostException e){
            System.out.println(e.toString());
        }catch(IOException e){
            System.out.println(e.toString());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogomovieMaxx;
    private javax.swing.JButton jBclose;
    private javax.swing.JButton jBsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMadm;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuIinsert;
    private javax.swing.JMenuItem jMenuItabout;
    private javax.swing.JMenuItem jMenuItadm;
    private javax.swing.JMenuItem jMenuItedelete;
    private javax.swing.JMenuItem jMenuItfun;
    private javax.swing.JMenuItem jMenuIthelp;
    private javax.swing.JMenu jMfunc;
    private javax.swing.JMenu jMhelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextAdesc;
    private javax.swing.JTextField jTsearch;
    // End of variables declaration//GEN-END:variables
}
