import java.io.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author M_M NYEMBO'S
 */
public class Server extends javax.swing.JFrame {
   serverConnection serC = new serverConnection();
   Connect Conn = new Connect();
   boolean state = true;
   
    public Server() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        initComponents();
        jPassword.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLuser = new javax.swing.JLabel();
        jLpass = new javax.swing.JLabel();
        jTuser = new javax.swing.JTextField();
        jBlogin = new javax.swing.JButton();
        jBstart = new javax.swing.JButton();
        jBstop = new javax.swing.JButton();
        jLserver = new javax.swing.JLabel();
        LogomovieMaxx = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 29, 55));

        jLuser.setBackground(new java.awt.Color(69, 73, 74));
        jLuser.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLuser.setForeground(new java.awt.Color(255, 255, 255));
        jLuser.setText("     Username");

        jLpass.setBackground(new java.awt.Color(69, 73, 74));
        jLpass.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLpass.setForeground(new java.awt.Color(255, 255, 255));
        jLpass.setText("     Password");

        jTuser.setBackground(new java.awt.Color(51, 51, 51));
        jTuser.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jTuser.setForeground(new java.awt.Color(255, 255, 255));
        jTuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTuserActionPerformed(evt);
            }
        });

        jBlogin.setBackground(new java.awt.Color(224, 120, 64));
        jBlogin.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jBlogin.setForeground(new java.awt.Color(255, 255, 255));
        jBlogin.setText("Login");
        jBlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBloginActionPerformed(evt);
            }
        });

        jBstart.setBackground(new java.awt.Color(224, 120, 64));
        jBstart.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jBstart.setForeground(new java.awt.Color(255, 255, 255));
        jBstart.setText("Start");
        jBstart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstartActionPerformed(evt);
            }
        });

        jBstop.setBackground(new java.awt.Color(224, 120, 64));
        jBstop.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jBstop.setForeground(new java.awt.Color(255, 255, 255));
        jBstop.setText("Stop");
        jBstop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstopActionPerformed(evt);
            }
        });

        jLserver.setBackground(new java.awt.Color(0, 51, 51));
        jLserver.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLserver.setForeground(new java.awt.Color(255, 255, 255));
        jLserver.setText("                      SERVER LOGIN");

        LogomovieMaxx.setIcon(new javax.swing.ImageIcon("C:\\Users\\M_M NYEMBO'S\\OneDrive\\Desktop\\free-vector-movie-max_066186_movie-max.png")); // NOI18N
        LogomovieMaxx.setToolTipText("Welcome, Please login and Enjoy !");

        jPassword.setBackground(new java.awt.Color(51, 51, 51));
        jPassword.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBstart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBstop))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLpass, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTuser)
                            .addComponent(jPassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLserver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogomovieMaxx, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLserver)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLuser)
                    .addComponent(jTuser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpass)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBstop)
                    .addComponent(jBstart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogomovieMaxx, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTuserActionPerformed

    private void jBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBloginActionPerformed
        String username = jTuser.getText();
        String password = jPassword.getText();
        String login = Conn.Login(username, password);
        
        if(login == "Ok"){
            JOptionPane.showMessageDialog(null, "Successful Login!");
            jBstart.setEnabled(true);
            jBstop.setEnabled(true);
            jBlogin.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Unsuccessful Login!");
            jTuser.setText("");
            jTuser.setFocusable(true);
            jPassword.setText("");
            jBstart.setEnabled(false);
            jBstop.setEnabled(false);

        }
        
    }//GEN-LAST:event_jBloginActionPerformed

    private void jBstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstopActionPerformed
        serC.stop();
    }//GEN-LAST:event_jBstopActionPerformed

    private void jBstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstartActionPerformed
        serC.start();
    }//GEN-LAST:event_jBstartActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogomovieMaxx;
    private javax.swing.JButton jBlogin;
    private javax.swing.JButton jBstart;
    private javax.swing.JButton jBstop;
    private javax.swing.JLabel jLpass;
    private javax.swing.JLabel jLserver;
    private javax.swing.JLabel jLuser;
    public static javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTuser;
    // End of variables declaration//GEN-END:variables
}
